name: 'Setup macOS Build Environment'
description: 'Sets up Rust and required dependencies for building ApertureC on macOS'
inputs:
  cache-key:
    description: 'Cache key for Rust dependencies'
    required: true
  save-cache:
    description: 'Whether to save cache (true/false). Defaults to saving only on main branch.'
    default: 'auto'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: ./.github/actions/setup-rust
      with:
        cache-key: ${{ inputs.cache-key }}
        install-home: ${{ runner.temp }}/..
        save-cache: ${{ inputs.save-cache }}
    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
      with:
        go-version: '1.22'
        cache: false
    - shell: bash
      run: ci/scripts/setup-macos-brew-deps.sh gtk4 protobuf pkg-config openssl@3
