name: 'Setup macOS Build Environment'
description: 'Sets up Rust and required dependencies for building ApertureC on macOS'
inputs:
  cache-key:
    description: 'Cache key for Rust dependencies'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: ./.github/actions/setup-rust
      with:
        cache-key: ${{ inputs.cache-key }}
        install-home: ${{ runner.temp }}/..
    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
      with:
        go-version: '1.22'
        cache: false
    - shell: bash
      run: brew install gtk+3 protobuf
    - shell: bash
      run: echo "PKG_CONFIG_PATH=/opt/homebrew/opt/openssl@3/lib/pkgconfig:/usr/local/opt/openssl@3/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
