ControlMessages DEFINITIONS AUTOMATIC TAGS ::= BEGIN
  IMPORTS ClientId, ClientCaps, Dimension, DurationMs, HeartbeatId, Location, SemVer, SequenceId FROM CommonTypes;

  OS ::= ENUMERATED {
    linux,
    windows,
    mac
  }

  Bitness ::= ENUMERATED {
    b32,
    b64 
  }

  Endianness ::= ENUMERATED {
    big,
    little
  }

  Architecture ::= ENUMERATED {
    x86,
    arm
  }

  ClientInfo ::= SEQUENCE {
    version SemVer,
    buildId UTF8String,
    os OS,
    osVersion UTF8String,
    sslLibrary UTF8String,
    sslVersion UTF8String,
    bitness Bitness,
    endianness Endianness,
    architecture Architecture,
    cpuId UTF8String,
    numberOfCores INTEGER (1..MAX),
    amountOfRam UTF8String,
    displaySize Dimension
  }

  ClientInit ::= SEQUENCE {
    tempId ClientId,
    clientInfo ClientInfo,
    clientCaps ClientCaps,
    clientHeartbeatInterval DurationMs,
    clientHeartbeatResponseInterval DurationMs
  }

  ClientGoodbyeReason ::= ENUMERATED {
    userRequested,
    terminating
  }

  ClientGoodbye ::= SEQUENCE {
    clientId ClientId,
    reason ClientGoodbyeReason
  }

  HeartbeatResponse ::= SEQUENCE {
    heartbeatId HeartbeatId,
    lastSequenceId SequenceId
  }

  FramebufferUpdateRequest ::= SEQUENCE {
    location Location,
    dimension Dimension
  }

  MissedFrameReport ::= SEQUENCE {
    sequenceIds SEQUENCE OF SequenceId
  }

  ClientToServerMessage ::= CHOICE {
    clientInit ClientInit,
    clientGoodbye ClientGoodbye,
    heartbeatResponse HeartbeatResponse,
    framebufferUpdateRequest FramebufferUpdateRequest,
    missedFrameReport MissedFrameReport
  }

  ServerInit ::= SEQUENCE {
    clientId ClientId,
    serverName UTF8String
  }

  ServerGoodbyeReason ::= ENUMERATED {
    serverShuttingDown
  }

  ServerGoodbye ::= SEQUENCE {
    reason ServerGoodbyeReason 
  }

  HeartbeatRequest ::= SEQUENCE {
    requestId HeartbeatId
  }

  ServerToClientMessage ::= CHOICE {
    serverInit ServerInit,
    serverGoodbye ServerGoodbye,
    heartbeatRequest HeartbeatRequest
  }

END
