name: 'Setup Rust'
description: 'Performs some common steps to setup a Rust environment on images already containing rustup'
inputs:
  toolchain:
    description: 'Toolchain to target'
    default: 'stable'
    required: false
  components:
    description: 'Comma-separated list of Rust components to install (e.g., rustfmt,clippy)'
    required: false
  cargo-packages:
    description:  'Comma-separated list of Cargo packages to install (e.g., cargo-deny)'
    required: false
  cache-key:
    description: 'Cache key'
    required: false
  install-home:
    description: 'Home directory for Rust installation (defaults to /root for Docker-based builds)'
    default: '/root'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Setup Rust environment
      shell: bash
      run: |
        echo "RUSTUP_HOME=${{ inputs.install-home }}/.rustup" >> $GITHUB_ENV
        echo "CARGO_HOME=${{ inputs.install-home }}/.cargo" >> $GITHUB_ENV
        echo "${{ inputs.install-home }}/.cargo/bin" >> $GITHUB_PATH
    - name: Default toolchain
      shell: bash
      run: rustup default ${{ inputs.toolchain }}
    - name: Add Rustup components
      if: inputs.components
      shell: bash
      run: rustup component add ${{ inputs.components }}
    - name: Install Cargo packages
      if: inputs.cargo-packages
      shell: bash
      run: cargo install ${{ inputs.cargo-packages }}
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
        shared-key: ${{ inputs.cache-key }}
        cache-bin: false
