name: 'Setup macOS Build Environment'
description: 'Sets up the macOS build environment with Rust, system dependencies, and caching for ApertureC'

inputs:
  rust-components:
    description: 'Comma-separated list of Rust components to install (e.g., rustfmt,clippy)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0
      with:
        cache-on-failure: true
        prefix-key: 'macos-runners'
        shared-key: ${{ github.repository }}
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.rust-components }}
    - shell: bash
      run: |
        brew install gtk+3 protobuf
        echo "PKG_CONFIG_PATH=/opt/homebrew/opt/openssl@3/lib/pkgconfig:/usr/local/opt/openssl@3/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
      with:
        go-version: '1.22'
        cache: false
    - shell: bash
      run: |
        echo "HOMEBREW_NO_AUTO_UPDATE=1" >> $GITHUB_ENV
