name: 'Cargo Workspace Command'
description: 'Execute cargo commands on multiple packages in a workspace'
inputs:
  command:
    description: 'Cargo subcommand and any flags (e.g., "build", "test", "build --release")'
    required: true
  packages:
    description: 'Space-separated string of package names (e.g., join(matrix.crate_group.crates, " "))'
    required: true
  args:
    description: 'Additional arguments to pass after package flags (e.g., "--target x86_64-pc-windows-gnu")'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        packages="${{ inputs.packages }}"
        package_flags=$(printf -- '-p %q ' $packages)
        cargo ${{ inputs.command }} $package_flags ${{ inputs.args }}
