name: 'Build RPM Package'
description: 'Create an .rpm package using cargo-generate-rpm'
inputs:
  crate:
    description: 'Crate name to package'
    required: true
  output_dir:
    description: 'Output directory for .rpm file'
    required: true
    default: 'target/rpm'
runs:
  using: composite
  steps:
    - name: Build package
      shell: bash
      run: |
        mkdir -p ${{ inputs.output_dir }}
        if ! cargo generate-rpm -p ${{ inputs.crate }} \
          -o ${{ inputs.output_dir }}; then
          echo "::error::Failed to build .rpm package for ${{ inputs.crate }}"
          exit 1
        fi
